#!/usr/bin/env python3
"""Refresh ref_sheets.py from the Google Sheet Ref_Sheets tab."""

from datetime import datetime, timezone
import json
import re

SOURCE_SHEET_ID = "143py3t5oTsz0gAfp8VpSJlpR5VS8Z4tfl067pMtW1EE"
SOURCE_TAB_NAME = "Ref_Sheets"
TARGET_FILE = "ref_sheets.py"


def fetch_ref_rows(sheet_id: str = SOURCE_SHEET_ID, tab_name: str = SOURCE_TAB_NAME):
    # Imported lazily so build helpers can be imported/tested without gspread installed.
    from google_sheets_utils import get_gsheet_client

    client = get_gsheet_client()
    ws = client.open_by_key(sheet_id).worksheet(tab_name)
    values = ws.get_all_values()
    if not values:
        return [], []

    headers = [str(h).strip() for h in values[0]]
    rows = []
    for raw_row in values[1:]:
        padded = raw_row + [""] * (len(headers) - len(raw_row))
        row = {headers[i]: str(padded[i]).strip() for i in range(len(headers))}
        if any(v for v in row.values()):
            rows.append(row)
    return headers, rows


def _find_workbook_name_column(headers):
    for h in headers:
        normalized = re.sub(r"[^a-z0-9]+", "", h.lower())
        if normalized in ("workbookname", "workbook"):
            return h
    raise ValueError(f"Could not find workbook-name column in headers: {headers}")


def build_module_content(headers, rows):
    generated_at = datetime.now(timezone.utc).isoformat()
    workbook_col = _find_workbook_name_column(headers)
    lines = [
        '"""Reference workbook registry.\n\n'
        "Auto-generated by refresh_ref_sheets.py from Google Sheet `Ref_Sheets`.\n"
        '"""\n',
        f"# Generated at: {generated_at}\n\n",
        f"REF_SHEET_COLUMNS = {json.dumps(headers, ensure_ascii=False)}\n\n",
        "REF_SHEETS = {\n",
    ]

    for row in rows:
        name = str(row.get(workbook_col, "")).strip().upper()
        if not name:
            continue

        record = {h: str(row.get(h, "")).strip() for h in headers}

        # Keep TYPE consistently uppercase when present.
        if "TYPE" in record and record["TYPE"]:
            record["TYPE"] = record["TYPE"].upper()

        # Compatibility helper used by resolver.
        if "sheet_id" not in record or not record["sheet_id"]:
            record["sheet_id"] = record.get("URL", "") or record.get("url", "")

        lines.append(f"    {json.dumps(name)}: {json.dumps(record, ensure_ascii=False)},\n")

    lines.append("}\n")
    return "".join(lines)


def refresh_ref_sheets_file(target_file: str = TARGET_FILE):
    headers, rows = fetch_ref_rows()
    content = build_module_content(headers, rows)
    with open(target_file, "w", encoding="utf-8") as f:
        f.write(content)
    return len(rows)


if __name__ == "__main__":
    count = refresh_ref_sheets_file()
    print(f"✅ Ref sheets refreshed from Google Sheet. Rows processed: {count}")
