#!/usr/bin/env python3
"""Refresh ref_sheets.py from the Google Sheet Ref_Sheets tab."""

from datetime import datetime, timezone
import json
import re

SOURCE_SHEET_ID = "143py3t5oTsz0gAfp8VpSJlpR5VS8Z4tfl067pMtW1EE"
SOURCE_TAB_NAME = "Ref_Sheets"
TARGET_FILE = "ref_sheets.py"


def fetch_ref_rows(sheet_id: str = SOURCE_SHEET_ID, tab_name: str = SOURCE_TAB_NAME):
    # Imported lazily so build helpers can be imported/tested without gspread installed.
    from google_sheets_utils import get_gsheet_client

    client = get_gsheet_client()
    ws = client.open_by_key(sheet_id).worksheet(tab_name)
    return ws.get_all_records()


def build_module_content(rows):
    generated_at = datetime.now(timezone.utc).isoformat()
    lines = [
        '"""Reference workbook registry.\n\n'
        "Auto-generated by refresh_ref_sheets.py from Google Sheet `Ref_Sheets`.\n"
        '"""\n',
        f"# Generated at: {generated_at}\n\n",
        "REF_SHEETS = {\n",
    ]

    for row in rows:
        name = str(row.get("Workbook Name", "")).strip().upper()
        if not name:
            continue

        normalized = {}
        for raw_key, raw_value in row.items():
            key = re.sub(r"[^a-z0-9]+", "_", str(raw_key).strip().lower()).strip("_")
            normalized[key] = str(raw_value).strip()

        if "url" in normalized and "sheet_id" not in normalized:
            normalized["sheet_id"] = normalized["url"]

        # Keep TYPE consistently uppercase when present.
        if "type" in normalized:
            normalized["type"] = normalized["type"].upper()

        lines.append(f"    {json.dumps(name)}: {json.dumps(normalized, ensure_ascii=False)},\n")

    lines.append("}\n")
    return "".join(lines)


def refresh_ref_sheets_file(target_file: str = TARGET_FILE):
    rows = fetch_ref_rows()
    content = build_module_content(rows)
    with open(target_file, "w", encoding="utf-8") as f:
        f.write(content)
    return len(rows)


if __name__ == "__main__":
    count = refresh_ref_sheets_file()
    print(f"✅ Ref sheets refreshed from Google Sheet. Rows processed: {count}")
