name: Manual Script Runner

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Full command to run (e.g. python3 fetch_holdings.py)"
        required: true
        default: "python3 fetch_holdings.py"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Google Chrome
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install
          google-chrome --version

      - name: Install dependencies
        run: |
          pip install gspread gspread-formatting kiteconnect pandas requests retrying tqdm \
            google-auth google-auth-oauthlib google-auth-httplib2 webdriver-manager selenium pyotp

      - name: Recreate secret files
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CREDS_JSON: ${{ secrets.CREDS_JSON }}
          SMTP_TOKEN_JSON: ${{ secrets.SMTP_TOKEN_JSON }}
       run: |
          mkdir -p /Users/sugamkuchhal/Documents/kite-gtt-demo
          [ -n "$API_KEY" ] && echo "$API_KEY" > /Users/sugamkuchhal/Documents/kite-gtt-demo/api_key.txt || true
          [ -n "$ACCESS_TOKEN" ] && echo "$ACCESS_TOKEN" > /Users/sugamkuchhal/Documents/kite-gtt-demo/access_token.txt || true
          [ -n "$CREDS_JSON" ] && echo "$CREDS_JSON" > /Users/sugamkuchhal/Documents/kite-gtt-demo/creds.json || true
          [ -n "$SMTP_TOKEN_JSON" ] && echo "$SMTP_TOKEN_JSON" > /Users/sugamkuchhal/Documents/kite-gtt-demo/smtp_token.json || true

      - name: Run your command
        run: ${{ github.event.inputs.command }}
